FROM mysql:8.0

# Instance 1
ENV MYSQL_ROOT_PASSWORD=root_pass
ENV MYSQL_DATABASE=db1
ENV MYSQL_USER=user1
ENV MYSQL_PASSWORD=pass1

# Instance 2
ENV MYSQL_ROOT_PASSWORD=root_pass
ENV MYSQL_DATABASE=db2
ENV MYSQL_USER=user2
ENV MYSQL_PASSWORD=pass2

# Instance 3
ENV MYSQL_ROOT_PASSWORD=root_pass
ENV MYSQL_DATABASE=db3
ENV MYSQL_USER=user3
ENV MYSQL_PASSWORD=pass3

# Instance 4
ENV MYSQL_ROOT_PASSWORD=root_pass
ENV MYSQL_DATABASE=db4
ENV MYSQL_USER=sa_user
ENV MYSQL_PASSWORD=sa_pass

# Instance 5
ENV MYSQL_ROOT_PASSWORD=root_pass
ENV MYSQL_DATABASE=db5
ENV MYSQL_USER=sa_user
ENV MYSQL_PASSWORD=sa_pass
