FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=root_password

ENV MYSQL_USER=user1
ENV MYSQL_PASSWORD=password1
ENV MYSQL_DATABASE=db1

ENV MYSQL_USER_2=user2
ENV MYSQL_PASSWORD_2=password2

EXPOSE 3306

CMD ["mysqld"]
